<?php
	$title = 'Delete Category';
	$this->headTitle($title);
?>
<h1><?php echo $this->escape($title); ?></h1>
<p>Are you sure that you want to delete category 
'<?php echo $this->escape($category['category_title']); ?>'?
</p>
<?php
$url = $this->url('default',
array('controller' => 'admincp-category', 'action' => 'delete')); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo (int)$category['category_id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>