<?php 
// initiate the adapter
$translate = new \Zend\View\Helper\Translator($this->adapter);
print $translate->translate('hello'); // this returns 'einfach'
//     echo 'Disk Capacity: ';
//     foreach ($this->diskCapacity as $key => $dc)
//     {
//         echo $key . ' : ' . $dc/102400 .'<br>';
//     }    
//     echo '<br>';
//     echo 'PHP Memory: ';
//     foreach ($this->phpMemory as $key => $pm)
//     {
//         echo $key . ' : ' . $pm/102400 .'<br>';
//     }
//     echo '<br>';
//     echo 'System Memory'; 
//     foreach($this->sysMemory as $key => $sm)
//     {
//         echo $key . ' : ' . $sm/102400 .'<br>';
//     }
?>