<?php
	$title = 'Edit Content';
	$this->headTitle($title);
?>
<h1><?php echo $this->escape($title); ?></h1>
	<style type="text/css">


	.multipleSelectBoxControl span{	/* Labels above select boxes*/
		font-family:arial;
		font-size:11px;
		font-weight:bold;
		width: 100%;
	}
	.multipleSelectBoxControl div select{	/* Select box layout */
		font-family:arial;
		height:100%;
	}
	.multipleSelectBoxControl input{	/* Small butons */
		width:25px;	
	}
	
	.multipleSelectBoxControl div{
		float:left;
	}
		
	.multipleSelectBoxDiv {
		
}
	</style>
	<script type="text/javascript">
	
	/************************************************************************************************************
	(C) www.dhtmlgoodies.com, October 2005
	
	This is a script from www.dhtmlgoodies.com. You will find this and a lot of other scripts at our website.	
	
	Terms of use:
	You are free to use this script as long as the copyright message is kept intact. However, you may not
	redistribute, sell or repost it without our permission.
	
	Thank you!
	
	www.dhtmlgoodies.com
	Alf Magne Kalleland
	
	************************************************************************************************************/
	
		
	var fromBoxArray = new Array();
	var toBoxArray = new Array();
	var selectBoxIndex = 0;
	var arrayOfItemsToSelect = new Array();
	
	
	function moveSingleElement()
	{
		var selectBoxIndex = this.parentNode.parentNode.id.replace(/[^\d]/g,'');
		var tmpFromBox;
		var tmpToBox;
		if(this.tagName.toLowerCase()=='select'){			
			tmpFromBox = this;
			if(tmpFromBox==fromBoxArray[selectBoxIndex])tmpToBox = toBoxArray[selectBoxIndex]; else tmpToBox = fromBoxArray[selectBoxIndex];
		}else{
		
			if(this.value.indexOf('>')>=0){
				tmpFromBox = fromBoxArray[selectBoxIndex];
				tmpToBox = toBoxArray[selectBoxIndex];			
			}else{
				tmpFromBox = toBoxArray[selectBoxIndex];
				tmpToBox = fromBoxArray[selectBoxIndex];	
			}
		}
		
		for(var no=0;no<tmpFromBox.options.length;no++){
			if(tmpFromBox.options[no].selected){
				tmpFromBox.options[no].selected = false;
				tmpToBox.options[tmpToBox.options.length] = new Option(tmpFromBox.options[no].text,tmpFromBox.options[no].value);
				
				for(var no2=no;no2<(tmpFromBox.options.length-1);no2++){
					tmpFromBox.options[no2].value = tmpFromBox.options[no2+1].value;
					tmpFromBox.options[no2].text = tmpFromBox.options[no2+1].text;
					tmpFromBox.options[no2].selected = tmpFromBox.options[no2+1].selected;
				}
				no = no -1;
				tmpFromBox.options.length = tmpFromBox.options.length-1;
											
			}			
		}
		
		
		var tmpTextArray = new Array();
		for(var no=0;no<tmpFromBox.options.length;no++){
			tmpTextArray.push(tmpFromBox.options[no].text + '___' + tmpFromBox.options[no].value);			
		}
		tmpTextArray.sort();
		var tmpTextArray2 = new Array();
		for(var no=0;no<tmpToBox.options.length;no++){
			tmpTextArray2.push(tmpToBox.options[no].text + '___' + tmpToBox.options[no].value);			
		}		
		tmpTextArray2.sort();
		
		for(var no=0;no<tmpTextArray.length;no++){
			var items = tmpTextArray[no].split('___');
			tmpFromBox.options[no] = new Option(items[0],items[1]);
			
		}		
		
		for(var no=0;no<tmpTextArray2.length;no++){
			var items = tmpTextArray2[no].split('___');
			tmpToBox.options[no] = new Option(items[0],items[1]);			
		}
	}
	
	function sortAllElement(boxRef)
	{
		var tmpTextArray2 = new Array();
		for(var no=0;no<boxRef.options.length;no++){
			tmpTextArray2.push(boxRef.options[no].text + '___' + boxRef.options[no].value);			
		}		
		tmpTextArray2.sort();		
		for(var no=0;no<tmpTextArray2.length;no++){
			var items = tmpTextArray2[no].split('___');
			boxRef.options[no] = new Option(items[0],items[1]);			
		}		
		
	}
	function moveAllElements()
	{
		var selectBoxIndex = this.parentNode.parentNode.id.replace(/[^\d]/g,'');
		var tmpFromBox;
		var tmpToBox;		
		if(this.value.indexOf('>')>=0){
			tmpFromBox = fromBoxArray[selectBoxIndex];
			tmpToBox = toBoxArray[selectBoxIndex];			
		}else{
			tmpFromBox = toBoxArray[selectBoxIndex];
			tmpToBox = fromBoxArray[selectBoxIndex];	
		}
		
		for(var no=0;no<tmpFromBox.options.length;no++){
			tmpToBox.options[tmpToBox.options.length] = new Option(tmpFromBox.options[no].text,tmpFromBox.options[no].value);			
		}	
		
		tmpFromBox.options.length=0;
		sortAllElement(tmpToBox);
		
	}
	
	
	/* This function highlights options in the "to-boxes". It is needed if the values should be remembered after submit. Call this function onsubmit for your form */
	function multipleSelectOnSubmit()
	{
		for(var no=0;no<arrayOfItemsToSelect.length;no++){
			var obj = arrayOfItemsToSelect[no];
			for(var no2=0;no2<obj.options.length;no2++){
				obj.options[no2].selected = true;
			}
		}
		
	}
	
	function createMovableOptions(fromBox,toBox,totalWidth,totalHeight,labelLeft,labelRight)
	{		
		fromObj = document.getElementById(fromBox);
		toObj = document.getElementById(toBox);
		
		arrayOfItemsToSelect[arrayOfItemsToSelect.length] = toObj;

		
		fromObj.ondblclick = moveSingleElement;
		toObj.ondblclick = moveSingleElement;

		
		fromBoxArray.push(fromObj);
		toBoxArray.push(toObj);
		
		var parentEl = fromObj.parentNode;
		
		var parentDiv = document.createElement('DIV');
		parentDiv.className='multipleSelectBoxControl';
		parentDiv.id = 'selectBoxGroup' + selectBoxIndex;
		//parentDiv.style.width = totalWidth + 'px';
		parentDiv.style.height = totalHeight + 'px';
		parentEl.insertBefore(parentDiv,fromObj);
		
		
		var subDiv = document.createElement('DIV');
		subDiv.style.width = (Math.floor(totalWidth/2) - 15) + 'px';
		fromObj.style.width = (Math.floor(totalWidth/2) - 15) + 'px';

		var label = document.createElement('SPAN');
		label.innerHTML = labelLeft;
		subDiv.appendChild(label);
		
		subDiv.appendChild(fromObj);
		subDiv.className = 'multipleSelectBoxDiv';
		parentDiv.appendChild(subDiv);
		
		
		var buttonDiv = document.createElement('DIV');
		buttonDiv.style.verticalAlign = 'middle';
		buttonDiv.style.paddingTop = (totalHeight/2) - 50 + 'px';
		buttonDiv.style.width = '30px';
		buttonDiv.style.textAlign = 'center';
		buttonDiv.style.margin = '0px 96px';
		parentDiv.appendChild(buttonDiv);
		
		var buttonRight = document.createElement('INPUT');
		buttonRight.type='button';
		buttonRight.value = '>';
		buttonDiv.appendChild(buttonRight);	
		buttonRight.onclick = moveSingleElement;	
		
		var buttonAllRight = document.createElement('INPUT');
		buttonAllRight.type='button';
		buttonAllRight.value = '>>';
		buttonAllRight.onclick = moveAllElements;
		buttonDiv.appendChild(buttonAllRight);		
		
		var buttonLeft = document.createElement('INPUT');
		buttonLeft.style.marginTop='10px';
		buttonLeft.type='button';
		buttonLeft.value = '<';
		buttonLeft.onclick = moveSingleElement;
		buttonDiv.appendChild(buttonLeft);		
		
		var buttonAllLeft = document.createElement('INPUT');
		buttonAllLeft.type='button';
		buttonAllLeft.value = '<<';
		buttonAllLeft.onclick = moveAllElements;
		buttonDiv.appendChild(buttonAllLeft);
		
		var subDiv = document.createElement('DIV');
		subDiv.style.width = (Math.floor(totalWidth/2) - 15) + 'px';
		toObj.style.width = (Math.floor(totalWidth/2) - 15) + 'px';
		toObj.style.float = 'right';

		var label = document.createElement('SPAN');
		label.innerHTML = labelRight;
		subDiv.appendChild(label);
				
		subDiv.appendChild(toObj);
		parentDiv.appendChild(subDiv);		
		
		toObj.style.height = (totalHeight - label.offsetHeight) + 'px';
		fromObj.style.height = (totalHeight - label.offsetHeight) + 'px';

			
		selectBoxIndex++;
		
	}
	
	
	
	</script>	
<style type="text/css">
#contentForm {
	position: relative;
	float: left;
	width: 695px;
	/*border: 1px solid #CCCCCC;*/
}

.leftForm {
	float: left;
	width: 440px;
	/*border: 1px solid #CCCCCC;
	background: #f9f9f9;*/
	padding: 5px;	
	margin-right: 10px;
}

.rightForm {
	float: left;
	width: 220px;
	border: 1px solid #CCCCCC;
	background: #f9f9f9;
	padding: 5px;
}
.submitFrom {
	position: relative;
	float: left;
	width: 695px;
	text-align: center;
}
.cleared {
	clear:both;
}
label.cform {
	width: 105px;
	margin-right: 10px;
	text-align: left;
}
input.cform {
	min-width: 120px;
	width:68%;
}
textarea.cform {
	min-width: 120x;
	width:68%;
}
select.cform {
	float: left;
}
select.categorySelectBox {
	height: 100px;
}
</style>
<?php //echo "<pre>"; var_dump($contents); die();?>
<form action="<?php echo $this->url('default', array('controller' => 'admincp-content', 'action' => 'edit')) ?>" method="post" onsubmit="multipleSelectOnSubmit()">
	<div id="contentForm">
		<div class="leftForm">
			<label class="cform">Title:</label>
			<input name="title" id="title" class="cform" value="<?php echo $contents['title'] ?>"/>
			<div class="cleared">&nbsp;</div>
			
			<label class="cform">Alias:</label>
			<input name="alias" id="alias" class="cform" value="<?php echo $contents['alias'] ?>"/>
			<div class="cleared">&nbsp;</div>
			
			<label class="cform">Summary:</label>
			<div style="float: left; z-index:999">
			<?php echo $this->ckeditor('summary',$contents['summary']); ?>
			</div>
			<div class="cleared">&nbsp;</div>
			
			<label class="cform">Content:</label>
			<div style="float: left; z-index:999">
			<?php echo $this->ckeditor('content',$contents['content']); ?>
			</div>
			<div class="cleared">&nbsp;</div>
			
			<label class="cform">Content Type:</label> 
			<select name="contentTypeIds" class="cform">
				<?php foreach ($this->contentType as $type) {
				    if ($status->content_type_id == $contents['type_checked']) {
						echo '<option value="'.$type->content_type_id.'">'.$type->content_type_name.'</option>';
					} else {
						echo '<option value="'.$type->content_type_id.'">'.$type->content_type_name.'</option>';
					}
				}?>
			</select>
			<div class="cleared">&nbsp;</div>
			<label class="cform">Status:</label> 
			<select name="contentStatusIds" class="cform">
				<?php foreach ($this->contentStatus as $status) {
				    if ($status->content_status_id == $contents['status_checked']) {
						echo '<option value="'.$status->content_status_id.'" CHECKED>'.$status->status_title.'</option>';
				    } else {	
						echo '<option value="'.$status->content_status_id.'">'.$status->status_title.'</option>';
				    }	
				}?>
			</select>
			<div class="cleared">&nbsp;</div>
			<label class="cform">Hide from menu:</label>
			<?php if ($contents['hide_from_menu'] == 1) :?>
				<input type="checkbox" name="hideFromMenu" id="hideFromMenu" style="margin-top:10px;" CHECKED/>
			<?php else :?>	
				<input type="checkbox" name="hideFromMenu" id="hideFromMenu" style="margin-top:10px;"/>
			<?php endif; ?>	
			<div class="cleared">&nbsp;</div>	
					
		</div>
		<div class="rightForm">
			<label class="cform">Meta Title:</label>
			<input name="metaTitle" id="metaTitle" class="" value="<?php echo $contents['meta_title'] ?>"/>
			<div class="cleared">&nbsp;</div>
			
			<label class="cform">Meta Keyword:</label>
			<textarea name="metaKeyword" id="metaKeyword" class="" ><?php echo $contents['meta_keyword'] ?></textarea>
			<div class="cleared">&nbsp;</div>
			
			<label class="cform">Meta Description:</label>
			<textarea name="metaDescription" id="metaDescription" style="height: 100px;" class=""><?php echo $contents['meta_description'] ?></textarea>
			<div class="cleared">&nbsp;</div>
					
			<label class="cform">Start Date:</label>
			<input name="startDate" id="startDate" class="" value="<?php echo $contents['start_date'] ?>"/>
			<div class="cleared">&nbsp;</div>

			<label class="cform">Expiry Date:</label>
			<input name="expDate" id="expDate" class="" value="<?php echo $contents['expiry_date'] ?>"/>
			<div class="cleared">&nbsp;</div>
			
			<input type="hidden" name="id" id="content_id" class="" value="<?php echo $contents['content_id'] ?>"/>
			<input type="hidden" name="contentDetailId" id="contentDetailId" class="" value="<?php echo $contents['content_detail_id'] ?>"/>
		</div>
	</div>
	<div class="cleared">&nbsp;</div>	
	<div class="addCategory">
			<select name="fromCategories[]" id="fromCategories" class="cform" size="10" multiple>
				<?php foreach ($this->categories as $category) {
					echo '<option value="'.$category['category_id'].'">'.$category['category_title'].'</option>';
				}?>
			</select>		
			<select name="toCategories[]" id="toCategories" class="cform" size="10" multiple>
				<?php 
				foreach ($this->categoriesSelected as $key => $categorySelected) {
					echo '<option value="'.$categorySelected['category_id'].'">'.$categorySelected['category_title'].'</option>';
				}?>				
			</select>		
		
	</div>
	<div class="cleared">&nbsp;</div>	
	<div class="cleared">&nbsp;</div>	
	<div class="submitFrom">
		<input type="submit" value="Edit Content" id="submitbutton" name="content_submit">
	</div>
	
</form>
<script type="text/javascript">
createMovableOptions("fromCategories","toCategories",500,300,'Available Categories','Selected Categories');
</script>