<?php
	$title = 'Delete Content Type';
	$this->headTitle($title);
?>
<h1><?php echo $this->escape($title); ?></h1>
<p>Are you sure that you want to delete
'<?php echo $this->escape($contentType['content_type_name']); ?>' (
'<?php echo $this->escape($contentType['content_type_description']); ?>')?
</p>
<?php
$url = $this->url('default',
array('controller' => 'admincp-content-type', 'action' => 'delete')); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo (int)$contentType['content_type_id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>