
<div class="post-outer">
<div class="post hentry uncustomized-post-template">
<div class="title1">
<a name="5094595306310361594"></a>
<h2>
<a href="#"><?php echo $this->data['detail'][0]['title']?></a>
</h2>
<div class="postmeta">
<span class="author">
<span class="post-author vcard">
Posted by
<span class="fn">ThuyDX</span>
</span>
</span>
<span class="clock"> On <?php echo $this->data['content']['start_date']?></span>
<span class="comm">
<a onclick="" href="#" class="comment-link"></a>
</span>
</div>
<div class="clear"></div>
</div>
<div class="post-header">
<div class="post-header-line-1"></div>
</div>
<div class="cover">
<div class="entry">
<p></p><p><?php echo $this->data['detail'][0]['content']?>.</p>
<div style="clear: both;"></div>
</div>
<div class="post-footer">
<div class="post-footer-line post-footer-line-1">
<span class="reaction-buttons">
</span>
<span class="star-ratings">
</span>
<span class="post-backlinks post-comment-link">
</span>
<span class="post-icons">
<span class="item-control blog-admin pid-1217819146">
<a title="Edit Post" href="#">
<img width="18" height="18" src="<?php echo $this->basePath()?>/images/edit_allbkg.gif" class="icon-action" alt="">
</a>
</span>
</span>
</div>
<div class="post-footer-line post-footer-line-2">
<span class="post-labels">
Labels:
<a rel="tag" href="#">Lorem 1</a>,
<a rel="tag" href="#">Lorem 2</a>,
<a rel="tag" href="#">Lorem 3</a>
</span>

</div>
<div class="post-footer-line post-footer-line-3">
<span class="post-location">
</span>
</div>
</div>
</div>
</div>
</div>
